# Generated by Django 4.2.13 on 2024-06-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='purchase_link',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Purchase Link'),
            preserve_default=False,
        ),
    ]
