# Generated by Django 4.2.13 on 2024-06-19 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pore_diameter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BeadMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.beadmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='HardwareMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HardwareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JewelryString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JewelryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LinkJewelryJewelryString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.jewelry')),
                ('string', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.jewelrystring')),
            ],
        ),
        migrations.CreateModel(
            name='LinkJewelryHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.hardware')),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.jewelry')),
            ],
        ),
        migrations.CreateModel(
            name='LinkJewelryBead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('bead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.bead')),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.jewelry')),
            ],
        ),
        migrations.AddField(
            model_name='jewelry',
            name='beads',
            field=models.ManyToManyField(through='jewelries.LinkJewelryBead', to='jewelries.bead'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='hardwares',
            field=models.ManyToManyField(through='jewelries.LinkJewelryHardware', to='jewelries.hardware'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='serious',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.series'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='strings',
            field=models.ManyToManyField(through='jewelries.LinkJewelryJewelryString', to='jewelries.jewelrystring'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.jewelrytype'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.hardwaretype'),
        ),
        migrations.AddField(
            model_name='bead',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.beadmaterial'),
        ),
    ]
