# Generated by Django 4.2.13 on 2024-06-19 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.hardwarematerial'),
        ),
    ]
