# Generated by Django 4.2.13 on 2024-06-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelries', '0002_alter_hardware_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linkjewelryjewelrystring',
            old_name='string',
            new_name='jewelry_string',
        ),
        migrations.AlterUniqueTogether(
            name='linkjewelrybead',
            unique_together={('jewelry', 'bead')},
        ),
        migrations.AlterUniqueTogether(
            name='linkjewelryhardware',
            unique_together={('jewelry', 'hardware')},
        ),
        migrations.AlterUniqueTogether(
            name='linkjewelryjewelrystring',
            unique_together={('jewelry', 'jewelry_string')},
        ),
    ]
