# Generated by Django 4.2.13 on 2024-06-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelries', '0003_rename_string_linkjewelryjewelrystring_jewelry_string_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hardware',
            old_name='size',
            new_name='length',
        ),
        migrations.AddField(
            model_name='hardware',
            name='width',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkjewelryhardware',
            name='is_main',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
