# Generated by Django 4.2.13 on 2024-06-20 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelries', '0004_rename_size_hardware_length_hardware_width_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bead',
            options={'verbose_name': 'Bead', 'verbose_name_plural': 'Beads'},
        ),
        migrations.AlterModelOptions(
            name='beadmaterial',
            options={'verbose_name': 'Bead Material', 'verbose_name_plural': 'Bead Materials'},
        ),
        migrations.RemoveField(
            model_name='bead',
            name='link',
        ),
        migrations.AddField(
            model_name='bead',
            name='purcharse_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='Purcharse Link'),
        ),
        migrations.AlterField(
            model_name='bead',
            name='diameter',
            field=models.DecimalField(decimal_places=1, help_text='The unit is millimeter.', max_digits=10, verbose_name='Diameter'),
        ),
        migrations.AlterField(
            model_name='bead',
            name='length',
            field=models.DecimalField(decimal_places=1, help_text='The unit is millimeter.', max_digits=10, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='bead',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.beadmaterial', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='bead',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='bead',
            name='pore_diameter',
            field=models.DecimalField(decimal_places=1, help_text='The unit is millimeter.', max_digits=10, verbose_name='Pore diameter'),
        ),
        migrations.AlterField(
            model_name='bead',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='beadmaterial',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='link',
            field=models.URLField(blank=True, default='taobao.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jewelrystring',
            name='link',
            field=models.URLField(blank=True, default='taobao.com', max_length=255),
            preserve_default=False,
        ),
    ]
