# Generated by Django 4.2.13 on 2024-06-20 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelries', '0005_alter_bead_options_alter_beadmaterial_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardware',
            options={'verbose_name': 'Hardware', 'verbose_name_plural': 'Hardwares'},
        ),
        migrations.AlterModelOptions(
            name='hardwarematerial',
            options={'verbose_name': 'Hardware Material', 'verbose_name_plural': 'Hardware Materials'},
        ),
        migrations.AlterModelOptions(
            name='hardwaretype',
            options={'verbose_name': 'Hardware Type', 'verbose_name_plural': 'Hardware Types'},
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='link',
        ),
        migrations.AddField(
            model_name='hardware',
            name='purcharse_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='Purcharse Link'),
        ),
        migrations.AlterField(
            model_name='bead',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='length',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.hardwarematerial', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.hardwaretype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='width',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='hardwarematerial',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hardwaretype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
