# Generated by Django 4.2.13 on 2024-06-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelries', '0006_alter_hardware_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jewelrystring',
            options={'verbose_name': 'String', 'verbose_name_plural': 'Strings'},
        ),
        migrations.AlterModelOptions(
            name='jewelrytype',
            options={'verbose_name': 'Jewelry Type', 'verbose_name_plural': 'Jewelry Types'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'Serieses'},
        ),
        migrations.RemoveField(
            model_name='jewelrystring',
            name='link',
        ),
        migrations.AddField(
            model_name='jewelrystring',
            name='purcharse_link',
            field=models.URLField(blank=True, max_length=255, verbose_name='Purcharse Link'),
        ),
        migrations.AlterField(
            model_name='bead',
            name='pore_diameter',
            field=models.DecimalField(decimal_places=1, help_text='The unit is millimeter.', max_digits=10, verbose_name='Pore Diameter'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='length',
            field=models.DecimalField(decimal_places=1, help_text='The unit is millimeter.', max_digits=10, verbose_name='Length'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='width',
            field=models.DecimalField(decimal_places=1, help_text='The unit is millimeter.', max_digits=10, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='jewelrystring',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='jewelrystring',
            name='price',
            field=models.PositiveIntegerField(help_text='Price per mm', verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='jewelrytype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
