# Generated by Django 4.2.13 on 2024-06-20 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelries', '0007_alter_jewelrystring_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jewelry',
            options={'verbose_name': 'Jewelry', 'verbose_name_plural': 'Jewelry'},
        ),
        migrations.AlterModelOptions(
            name='linkjewelrybead',
            options={'verbose_name': 'Bead', 'verbose_name_plural': 'Beads'},
        ),
        migrations.AlterModelOptions(
            name='linkjewelryhardware',
            options={'verbose_name': 'Hardware', 'verbose_name_plural': 'Hardwares'},
        ),
        migrations.AlterModelOptions(
            name='linkjewelryjewelrystring',
            options={'verbose_name': 'Jewelry String', 'verbose_name_plural': 'Jewelry Strings'},
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='serious',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.series', verbose_name='Serious'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.jewelrytype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='linkjewelrybead',
            name='bead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.bead', verbose_name='Bead'),
        ),
        migrations.AlterField(
            model_name='linkjewelrybead',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='linkjewelryhardware',
            name='hardware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.hardware', verbose_name='Hardware'),
        ),
        migrations.AlterField(
            model_name='linkjewelryhardware',
            name='is_main',
            field=models.BooleanField(verbose_name='Is Main?'),
        ),
        migrations.AlterField(
            model_name='linkjewelryhardware',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='linkjewelryjewelrystring',
            name='jewelry_string',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelries.jewelrystring', verbose_name='Jewelry String'),
        ),
        migrations.AlterField(
            model_name='linkjewelryjewelrystring',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
    ]
