# Generated by Django 4.2.13 on 2024-06-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelries', '0008_alter_jewelry_options_alter_linkjewelrybead_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jewelrystring',
            options={'verbose_name': 'Jewelry String', 'verbose_name_plural': 'Jewelry Strings'},
        ),
    ]
