# Generated by Django 4.2.13 on 2024-06-20 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelries', '0009_alter_jewelrystring_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
    ]
