# Generated by Django 4.2.13 on 2024-06-20 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=1, help_text='The unit is millimeter.', max_digits=10, verbose_name='Length')),
                ('diameter', models.DecimalField(decimal_places=1, help_text='The unit is millimeter.', max_digits=10, verbose_name='Diameter')),
                ('pore_diameter', models.DecimalField(decimal_places=1, help_text='The unit is millimeter.', max_digits=10, verbose_name='Pore Diameter')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('purcharse_link', models.URLField(blank=True, max_length=255, verbose_name='Purcharse Link')),
            ],
            options={
                'verbose_name': 'Bead',
                'verbose_name_plural': 'Beads',
            },
        ),
        migrations.CreateModel(
            name='BeadMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Bead Material',
                'verbose_name_plural': 'Bead Materials',
            },
        ),
        migrations.CreateModel(
            name='BeadShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Bead Shape',
                'verbose_name_plural': 'Bead Shape',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=1, help_text='The unit is millimeter.', max_digits=10, verbose_name='Length')),
                ('width', models.DecimalField(decimal_places=1, help_text='The unit is millimeter.', max_digits=10, verbose_name='Width')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('purcharse_link', models.URLField(blank=True, max_length=255, verbose_name='Purcharse Link')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.color', verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Hardware',
                'verbose_name_plural': 'Hardwares',
            },
        ),
        migrations.CreateModel(
            name='HardwareMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Hardware Material',
                'verbose_name_plural': 'Hardware Materials',
            },
        ),
        migrations.CreateModel(
            name='HardwareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Hardware Type',
                'verbose_name_plural': 'Hardware Types',
            },
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Jewelry',
                'verbose_name_plural': 'Jewelry',
            },
        ),
        migrations.CreateModel(
            name='JewelryString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.DecimalField(decimal_places=1, help_text='The unit is millimeter.', max_digits=10, verbose_name='Diameter')),
                ('price', models.DecimalField(decimal_places=3, help_text='Price per mm', max_digits=10, verbose_name='Price')),
                ('purcharse_link', models.URLField(blank=True, max_length=255, verbose_name='Purcharse Link')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.color', verbose_name='Color')),
            ],
            options={
                'verbose_name': 'Jewelry String',
                'verbose_name_plural': 'Jewelry Strings',
            },
        ),
        migrations.CreateModel(
            name='JewelryStringType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Jewelry String Type',
                'verbose_name_plural': 'Jewelry String Types',
            },
        ),
        migrations.CreateModel(
            name='JewelryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Jewelry Type',
                'verbose_name_plural': 'Jewelry Types',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='LinkJewelryJewelryString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.jewelry')),
                ('jewelry_string', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.jewelrystring', verbose_name='Jewelry String')),
            ],
            options={
                'verbose_name': 'Jewelry String',
                'verbose_name_plural': 'Jewelry Strings',
                'unique_together': {('jewelry', 'jewelry_string')},
            },
        ),
        migrations.CreateModel(
            name='LinkJewelryHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('is_main', models.BooleanField(verbose_name='Is Main?')),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.hardware', verbose_name='Hardware')),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.jewelry')),
            ],
            options={
                'verbose_name': 'Hardware',
                'verbose_name_plural': 'Hardwares',
                'unique_together': {('jewelry', 'hardware')},
            },
        ),
        migrations.CreateModel(
            name='LinkJewelryBead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('bead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.bead', verbose_name='Bead')),
                ('jewelry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.jewelry')),
            ],
            options={
                'verbose_name': 'Bead',
                'verbose_name_plural': 'Beads',
                'unique_together': {('jewelry', 'bead')},
            },
        ),
        migrations.AddField(
            model_name='jewelrystring',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.jewelrystringtype', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='beads',
            field=models.ManyToManyField(through='jewelry.LinkJewelryBead', to='jewelry.bead'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='hardwares',
            field=models.ManyToManyField(through='jewelry.LinkJewelryHardware', to='jewelry.hardware'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='serious',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.series', verbose_name='Serious'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='strings',
            field=models.ManyToManyField(through='jewelry.LinkJewelryJewelryString', to='jewelry.jewelrystring'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.jewelrytype', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.hardwarematerial', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.hardwaretype', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='bead',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.color', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='bead',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.beadmaterial', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='bead',
            name='shape',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.beadshape', verbose_name='Shape'),
        ),
    ]
