# Generated by Django 4.2.13 on 2024-06-20 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeadShapeAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Bead Shape Attribute',
                'verbose_name_plural': 'Bead Shape Attributes',
            },
        ),
        migrations.AddField(
            model_name='bead',
            name='shape_attribute',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='jewelry.beadshapeattribute', verbose_name='Shape Attribute'),
            preserve_default=False,
        ),
    ]
