# Generated by Django 4.2.13 on 2024-06-20 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0003_alter_beadshape_options_remove_bead_shape_attribute_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='linkjewelryjewelrystring',
            unique_together=set(),
        ),
    ]
