# Generated by Django 4.2.13 on 2024-06-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0005_alter_bead_purchase_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bead',
            name='purchase_link',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Purchase Link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hardware',
            name='purchase_link',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Purchase Link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jewelrystring',
            name='purchase_link',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Purchase Link'),
            preserve_default=False,
        ),
    ]
