# Generated by Django 4.2.13 on 2024-06-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0006_alter_bead_purchase_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
