# Generated by Django 4.2.13 on 2024-06-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0007_jewelry_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='length',
            field=models.PositiveIntegerField(default=0, verbose_name='Length'),
            preserve_default=False,
        ),
    ]
