# Generated by Django 4.2.13 on 2024-06-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0008_jewelry_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='length',
            field=models.PositiveIntegerField(help_text='The unit is millimeter.', verbose_name='Length'),
        ),
    ]
