# Generated by Django 4.2.13 on 2024-06-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0009_jewelry_title_alter_jewelry_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='introduction',
            field=models.TextField(default='', verbose_name='Introduction'),
            preserve_default=False,
        ),
    ]
