# Generated by Django 4.2.13 on 2024-06-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0010_jewelry_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='inspiration',
            field=models.TextField(blank=True, null=True, verbose_name='Inspiration'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='Introduction'),
        ),
    ]
