# Generated by Django 4.2.13 on 2024-06-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0011_jewelry_inspiration_alter_jewelry_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='inspiration',
            field=models.TextField(blank=True, default='', verbose_name='Inspiration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='introduction',
            field=models.TextField(blank=True, default='', verbose_name='Introduction'),
            preserve_default=False,
        ),
    ]
