# Generated by Django 4.2.13 on 2024-06-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0012_alter_jewelry_inspiration_alter_jewelry_introduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jewelry',
            old_name='serious',
            new_name='series',
        ),
    ]
